services:
  webapp1:
    image: nginx:alpine
    container_name: webapp1
    volumes:
      - ./webapp1/html:/usr/share/nginx/html:ro      
    networks:
      - proxy-net

  webapp2:
    image: nginx:alpine
    container_name: webapp2
    volumes:
      - ./webapp2/html:/usr/share/nginx/html:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
